CREATE TABLE IF NOT EXISTS Identify (
    UserID VARCHAR(255) PRIMARY KEY,
    Address VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS Mosaic (
    MosaicID VARCHAR(255) NOT NULL PRIMARY KEY,
    CreateTime DATETIME NOT NULL,
    ExpireTime DATETIME NOT NULL
);
CREATE TABLE IF NOT EXISTS Photos (
    PhotoID INT AUTO_INCREMENT PRIMARY KEY,
    UserID VARCHAR(255),
    PhotoPath VARCHAR(500),
    Comment TEXT,
    BidUserID VARCHAR(255),
    Amount INT,
    FOREIGN KEY (UserID) REFERENCES Identify(UserID),
    FOREIGN KEY (BidUserID) REFERENCES Identify(UserID)

);

CREATE TABLE IF NOT EXISTS Vote (
    UserID VARCHAR(255) NOT NULL PRIMARY KEY,
    Vote BOOLEAN NOT NULL DEFAULT FALSE,
    Give BOOLEAN NOT NULL DEFAULT FALSE,
    FOREIGN KEY (UserID) REFERENCES Identify(UserID)
);

CREATE TABLE IF NOT EXISTS Bought (
    PhotoID INT NOT NULL PRIMARY KEY,
    UserID VARCHAR(255),
    PhotoPath VARCHAR(500),
    BoughtAmount INT,
    FOREIGN KEY (UserID) REFERENCES Identify(UserID),
    FOREIGN KEY (PhotoID) REFERENCES Photos(PhotoID)
);

