CREATE TABLE IF NOT EXISTS Identify (
    Address VARCHAR(255) NOT NULL UNIQUE PRIMARY KEY
);

CREATE TABLE IF NOT EXISTS Mosaic (
    MosaicID VARCHAR(255) NOT NULL PRIMARY KEY,
    CreateTime DATETIME NOT NULL,
    ExpireTime DATETIME NOT NULL
);
CREATE TABLE IF NOT EXISTS Photos (
    PhotoID INT AUTO_INCREMENT PRIMARY KEY,
    MosaicID VARCHAR(255) NOT NULL,
    Address VARCHAR(255),
    PhotoPath VARCHAR(500),
    Comment TEXT,
    BidUserID VARCHAR(255),
    Amount INT,
    Purchased BOOLEAN NOT NULL DEFAULT FALSE,
    FOREIGN KEY (Address) REFERENCES Identify(Address),
    FOREIGN KEY (BidUserID) REFERENCES Identify(Address),
    FOREIGN KEY (MosaicID) REFERENCES Mosaic(MosaicID)
);

CREATE TABLE IF NOT EXISTS Vote (
    Address VARCHAR(255) NOT NULL PRIMARY KEY,
    Vote BOOLEAN NOT NULL DEFAULT FALSE,
    Give BOOLEAN NOT NULL DEFAULT FALSE,
    FOREIGN KEY (Address) REFERENCES Identify(Address)
);

CREATE TABLE IF NOT EXISTS Bought (
    PhotoID INT NOT NULL PRIMARY KEY,
    Address VARCHAR(255),
    PhotoPath VARCHAR(500),
    BoughtAmount INT,
    FOREIGN KEY (Address) REFERENCES Identify(Address),
    FOREIGN KEY (PhotoID) REFERENCES Photos(PhotoID)
);

