server {
    listen 80;
    client_max_body_size 20m;

    root /usr/share/nginx/html;
    index index.html;

    location /Register/ {
        proxy_pass http://backend:5001/Register/;
    }

    location /Login/ {
        proxy_pass http://backend:5001/Login/;
    }

    location /Tournament/ {
        proxy_pass http://backend:5001/Tournament/;
    }

    location /Auction/ {
        proxy_pass http://backend:5001/Auction/;
    }

    location /AuctionBuy/ {
        proxy_pass http://backend:5001/AuctionBuy/;
    }

    location /icons/ {
        alias /usr/share/nginx/html/icons/;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
    proxy_read_timeout 120s;
    proxy_connect_timeout 120s;
    proxy_send_timeout 120s;
}